### ISSUE TITLE
Disable rate limitation counts when the grader makes requests

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#10]
I just noticed that one participant's submissions was marked as failed with the error message : "Model received too many requests".
On a closer look, it turns out, the attacker had used up just his quota of requests. And the error was thrown when the evaluator was using the model to test the adversarial images.

Can we have a shared secret which disables the rate limit checking for certain trusted agents ?
@bveliqi 

Or to keep it simple, should we just increase the max number of allowed predictions by the number of images in the test set ?

**Comment by bveliqi** [comment]
We could have a shared secret and it would definitely be the nicer solution, however I think increasing the allowed predictions should be more than enough for this case. The attack could do more predictions requests than actually allowed, however the grader would fail as happened in the above example but rightly so now.

**Comment by spMohanty** [comment]
Increased Quota of 10,500 predictions implemented on the server.

(Ref: https://github.com/bethgelab/adversarial-vision-challenge/commit/997c8809f20bd5bafcba6119e9f0b8a5334ccd7d)

**Comment by bveliqi** [comment]
Actually, i'll just talked to @jonasrauber more intensively about this, and we decided that we should rather go with a shared secret. I'll reopen the issue and update it once implemented. Once done, we can reset the quota to the original value.

**Comment by bveliqi** [comment]
Closing this again, see #16.
