### ISSUE TITLE
Increase time in attacks

### ISSUE THREAD

**Issue by ivan-v-kush** [bveliqi/adversarial-vision-challenge#11]
I needed to increase timeouts in attacks. Only after this I got message about succesfull tests.
Use **pointwise_targeted_attack_baseline**

(here about increasing time in model evaluation https://github.com/bethgelab/adversarial-vision-challenge/issues/7)

**avc-test-attack:**
change values (1st came in mind and it worked)
19->50
21->80
10->40
```
 # check that results are written within time limit
            if num_results == 0 and time.time() - start_time > 50:
                raise RuntimeError('Results file not written with time limit'
                                   ' (20 seconds)- something went wrong!')
            elif time.time() - start_time > 80 and \
                    (time.time() - start_time) / float(len(result_files)) > 40:
                raise RuntimeError('Your attack is too slow'
                                   ' (> 10 seconds / sam.ple)!')
```

`time docker run --runtime=nvidia --rm nvidia/cuda echo ok` - takes 4 seconds.

**Comment by jonasrauber** [comment]
For the pointwise attack this is a known issue and we are still investigating this. The other baseline attacks should pass the tests without modifications.

**Comment by bveliqi** [comment]
@jonasrauber is this solved by now? can we close this issue?
