### ISSUE TITLE
correct attacks link on main page

### ISSUE THREAD

**Issue by ivan-v-kush** [bveliqi/adversarial-vision-challenge#12]
https://github.com/bethgelab/adversarial-vision-challenge

`for attacks: https://gitlab.crowdai.org/adversarial-vision-challenge/nips18-avc-attack-template`
gives 404

**Comment by bveliqi** [comment]
@IvanKush The link is working perfectly fine for me?

I'll close this issue for now, if it still occurs for you please reopen and we'll investigate.
