### ISSUE TITLE
Number of model queries in saltnpepper_untargeted_attack_baseline

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#14]
@jonasrauber : One of the participants noticed this because his submission was failing.
The current `saltnpepper_untargeted_attack_baseline` seems to be using ~267000 model queries and hence exceeding the rate limit.

```
@spMohanty : No problem, just submitted it.

Hmm, last time I tried it locally and I got the following results:

Your attack queried the model 53427 times (maximum allowed: 100000)
Number of adversarials 100 of 100
Median adversarial distances: 0.4123618347198499 (optimum = 50 / 255 = 0.196)

So this means that the attack takes 534 queries per adversarial example in average, 
and when I submit the attack to the server, it will take 
total 534*500 queries in the evaluation?  Maybe this is why 
the evaluation always stuck at 19X steps (534*19X > 100000)?
```

PS: Created the issue here instead of the relevant repository to ensure we have all the technical issues in a single place for future reference.

**Comment by spMohanty** [comment]
@bveliqi : Did you try submitting all the baseline attack models atleast, and having them accepted by the grader ?

**Comment by bveliqi** [comment]
@spMohanty No, I did not. I just try to test one for each track.
