### ISSUE TITLE
Add support for no-image-build and no-cache mode

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#18]
Ability to skip the image building process, and the ability to ignore the cache are very important especially when debugging.
We should allow both these through cli flags to all the scripts.

**Comment by bveliqi** [comment]
@spMohanty can we close this issue?

**Comment by spMohanty** [comment]
Fixed with https://github.com/bethgelab/adversarial-vision-challenge/commit/b3982ea78d277c5b81288c42cc4d2917ea340e9b
