### ISSUE TITLE
timeout - attack doesnt interact with the model server

### ISSUE THREAD

**Issue by bveliqi** [bveliqi/adversarial-vision-challenge#24]
Would it be possible to add a timeout of some sort, when an attack doesnt interact with the model server in a configurable T seconds/minutes ?

**Comment by bveliqi** [comment]
@spMohanty @wielandbrendel @jonasrauber Can any of you pls review #27 so we can close this ?

**Comment by spMohanty** [comment]
@bveliqi : I had added my reviews.

**Comment by bveliqi** [comment]
@spMohanty Where? I can't see any comments from you?

**Comment by spMohanty** [comment]
![35ad1acc-d04d-4185-8d20-9a4d3a12a054](https://user-images.githubusercontent.com/1581312/42999031-94980770-8c1c-11e8-992a-df1bf70e7c72.png)


You should be seeing the review on the pull request itself ?

**Comment by bveliqi** [comment]
Are you sure you've submitted your review with the comments? I can't see it.

**Comment by spMohanty** [comment]
Arrggg you are right. I had not "Added the review" for you to view. You should be able to see it now.

**Comment by bveliqi** [comment]
Still can't see anything. 🤷‍♂️

**Comment by youweixiansheng** [comment]
Didn't find that when you choice foolbox model with parameter bounds=(0,1) (note:pytorch) Every thing is wrong. Is't a bug?
"avc-test-model ." will end with a time out and no reply 
(note: "Adversarial Vision Challenge (Robust Model Track)" with resnet18_pytorch )
