### ISSUE TITLE
"optimum = 50/255" should be removed from avc-test-model-against-attack

### ISSUE THREAD

**Issue by csy530216** [bveliqi/adversarial-vision-challenge#34]
In `avc-test-model-against-attack`,
```python
    print('Median adversarial distances: {}'
          ' (optimum = 50 / 255 = 0.196)'.format(median))
```
I think the "optimum = 50 / 255 = 0.196" is only for `MockModel` in `avc-test-attack`, but for other models it is meaningless.
By the way, `avc-test-model-against-attack` is a very useful script, for both defence and attack. If its development has been completed, could you add it to the scripts to install in `setup.py`, and add its usage to docs?

**Comment by wielandbrendel** [comment]
Good points, thanks! @bveliqi or @jonasrauber : Could you take care of that?

**Comment by csy530216** [comment]
In fact, look at the following code:
```python
real_distances = np.array(real_distances)
distances = real_distances * 255
print('Number of adversarials {} of {}'.format(
    (distances > 50).sum(), distances.shape[0]))

median = np.median(real_distances[distances > 50])
print('Median adversarial distances: {}'
        ' (optimum = 50 / 255 = 0.196)'.format(median))
```
As a whole it should be modified accordingly. For example:
```python
real_distances = np.array(real_distances)
distances = real_distances * 255
print('Number of images originally correctly classified is {} of {}'.format(
    (distances > 0).sum(), distances.shape[0]))

median = np.median(real_distances)
print('Median adversarial distances: {}'.format(median))
```

**Comment by csy530216** [comment]
By the way I have another problem: in avc-test-attack and avc-test-model-against-attack,
```python
if np.isnan(median):
    print('distances: ', distances)
    sys.stdout.flush()
    raise RuntimeError('Your attack seems to have failed on more'
                        ' than half of the samples')
```
My understanding: if the result image does not exist, a FileNotFoundError will be thrown. If the assertion in load_image fails, the distance will be set as worst case distance (not NaN). Then the only case to cause NaN of distance is that the image itself contains NaN. So the error message should be changed to 'Your attack seems to have caused NaN on more than half of the samples'.
But I think both the NaN and the AssertionError in following codes (assertion is in `load_image` func in the script):
```python
try:
    adversarial = load_image('avc_results/{}'.format(file))
except AssertionError:
    print('adversarial for {} is invalid'.format(file))
    adversarial = None
if adversarial is None:
    _distance = float(worst_case_distance(original))
else:
    _distance = float(distance(original, adversarial))
real_distances.append(_distance)
```
will not happen when result images are generated using `store_adversarial`, for the existence of `check_image` in common.py:
```python
def check_image(image):
    # image should a 64 x 64 x 3 RGB image
    _assert(isinstance(
        image, np.ndarray), "image should be an numpy array")
    _assert(image.shape == (64, 64, 3), "image should be of size 64x64x3")
    if image.dtype == np.float32:
        # we accept float32, but only if the values
        # are between 0 and 255 and we convert them
        # to integers
        if image.min() < 0:
            logger.warning('clipped value smaller than 0 to 0')
        if image.max() > 255:
            logger.warning('clipped value greater than 255 to 255')
        image = np.clip(image, 0, 255)
        image = image.astype(np.uint8)
    assert image.dtype == np.uint8
    return image
```
I think the returned image will not contain NaN and must satisfy the assertions in `load_image` in the script. So in `avc-test-attack` and `avc-test-model-against-attack`, the check of NaN and assertions in `load_image` might be unnecessary.
By the way, in `store_adversarial` in utils.py:
```python
def store_adversarial(file_name, adversarial):
    """
        Given the filename, stores the adversarial as .npy file.
    """
    if adversarial is not None:
        adversarial = check_image(adversarial)

    output_folder = os.getenv('OUTPUT_ADVERSARIAL_PATH')
    path = os.path.join(output_folder, file_name)
    path_without_extension = os.path.splitext(path)[0]
    np.save(path_without_extension, adversarial)
    CrowdAiNotifier.store_adversarial(file_name)
```
If adversarial is None, what will happen? `np.save(path, None)` does not throw exception.

**Comment by csy530216** [comment]
Just another note: in `avc-test-model-against-attack`,
```python
if adversarial is None:
    _distance = float(worst_case_distance(original))
else:
    # test adversarial against model
    pred_label = fmodel(adversarial)
    _distance = float(distance(original, adversarial))
```
Here forget to check whether `pred_label != label`. Maybe the code is still under development:)

**Comment by csy530216** [comment]
Another note: in `avc-test-attack` , `avc-test-model` and `avc-test-model-against-attack`,
```python
repo2docker_args = ["--no-run", "--debug"]
if no_build:
    #TODO: Use logger instead of print statements
    print("WARNING: ", "Not building the docker image and assuming it is built and available at : {}".format(image_name))
    repo2docker_args.append("--no-build")
else:
    if no_cache:
        reset_repo2docker_cache()
        print('Building images (without cache)...')
    else:
        print('Building images from cache (if exists)...', end="")
    repo2docker_args.append(
        "--image-name {}".format(image_name)
    )
    cmd = "crowdai_repo2docker"
    cmd += " "
    cmd += " ".join(repo2docker_args)
    cmd += " "
    cmd += directory
    subprocess.check_call(
        "crowdai-repo2docker --no-run --image-name {} --debug {}".format(
            image_name, directory), shell=True)
    checkmark()
```
It seems that both `repo2docker_args` and `cmd` variables are not used, and the related lines can be deleted.

**Comment by jonasrauber** [comment]
`pred_label != label` does not need to be checked, foolbox performs this internally to make sure only valid adversarials are returned

**Comment by jonasrauber** [comment]
regarding unused variables: @bveliqi can you clean / fix the code?

**Comment by csy530216** [comment]
@jonasrauber About `pred_label != label`, if it does not need to be checked, then `pred_label = fmodel(adversarial)` could also be removed, as long as:
```python
    os.environ["MODEL_PORT"] = str(port)
    os.environ["MODEL_SERVER"] = ip
    fmodel = adversarial_vision_challenge.utils.load_model()
```
But I think it is still necessary to check, since one doesn't necessarily use foolbox to create the adversarial.
