### ISSUE TITLE
Can't submit.

### ISSUE THREAD

**Issue by zzd1992** [bveliqi/adversarial-vision-challenge#42]
I install this package via
```
pip3 install adversarial-vision-challenge --user
```
And I can import it successfully.
However, I can't run any command.
For example, when I run
```
avc-submit .
```
then
```
-bash: avc-submit: command not found
```
What's wrong?

**Comment by jonasrauber** [comment]
I guess `pip` installs the binaries (scripts) such as `avc_submit` into a folder that's not in your `PATH` environment variable. Just figure out where exactly (Google, …) and put it in your path.

**Comment by jonasrauber** [comment]
Assuming this is solved. Reopen if not.
