### ISSUE TITLE
Can we do preprocessing on input image for this year competition?

### ISSUE THREAD

**Issue by yxchng** [bveliqi/adversarial-vision-challenge#43]
From the way we submit, we need to wrap our model in a foolbox model and server it. This pipeline does not seem to be friendly to preprocessing. Are we allowed to do preprocessing and if so how? Or is it forbidden?

**Comment by wielandbrendel** [comment]
Preprocessing can always be part of the model, right? If that is somehow difficult, you can also wrap your model + preprocessing in your own compatible class (you do not need to use foolbox but the methods have to be compatible with the foolbox model API).
