### ISSUE TITLE
How to use c++ extension in nvidia-docker?

### ISSUE THREAD

**Issue by Maaater** [bveliqi/adversarial-vision-challenge#44]
I write a cpp extension for pytorch with ''from torch.utils.cpp_extension import load as load_ext'', however I found that there is no gcc or g++ in nvidia-docker. what should I do?

**Comment by jonasrauber** [comment]
You can install additional packages (by specifying them in the `apt.txt` file). Does that help?

**Comment by Maaater** [comment]
This problem is solved by adding 'g++' in apt.txt, Thanks a lot. @jonasrauber
