### ISSUE TITLE
avc-test-model error

### ISSUE THREAD

**Issue by yxd117** [bveliqi/adversarial-vision-challenge#45]
When I run the test, I got the following error in my log,

![image](https://user-images.githubusercontent.com/9412959/46065615-1d4ab500-c1a5-11e8-80c9-33d949d90683.png)

**Comment by jonasrauber** [comment]
Are you developing/testing a model, or an attack?

**Comment by yxd117** [comment]
> Are you developing/testing a model, or an attack?

I am testing a model, it's for robust model track.

**Comment by jonasrauber** [comment]
@bveliqi any idea?
