### ISSUE TITLE
Error with cuda extension in docker?

### ISSUE THREAD

**Issue by Maaater** [bveliqi/adversarial-vision-challenge#47]
I use jit to compile the cuda extension,but the server keeps trying.  I run into the image with 'NV_GPU=1 nvidia-docker  run -i -t --runtime=nvidia avc/model_submission /bin/bash' and find that there is no nvcc. What should I do?

**Comment by jonasrauber** [comment]
If you need something special like `nvcc` in your container, you might need to install it.

**Comment by Maaater** [comment]
will the `avc-test-model` do this for me?

**Comment by Maaater** [comment]
@jonasrauber Any ideas of submitting code with cuda extension in pytorch? It seems that images created by `crowdai-repo2docker` used in `avc-test-model` don't have nvcc, thus leading to the compiling error.  Similar problem of missing `gcc` is solved in #44 .

**Comment by spMohanty** [comment]
@maater : You can include a Dockefile in your repository, then crowdai-repo2docker will prioritize it and build it like you would with docker build. Let me know if it works for you.

**Comment by Maaater** [comment]
@spMohanty It works!  Thank you! The dockerfile is shown as below, it is based on 'nvidia/cuda:latest'
[Dockerfile.txt](https://github.com/bethgelab/adversarial-vision-challenge/files/2513680/Dockerfile.txt)
