### ISSUE TITLE
Attack crowdAINotifier to assert statements

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#9]
@bveliqi : There are a few assert statements throughout the whole code, and when they fail, the grading infrastructure wouldn't be notified of them.

Would it be possible to wrap them in a separate function ? And when the assertion fails, send the relevant message via `CrowdAiNotifier` ?

Something like : 
```python
def _assert(condition, message):
    try:
        assert condition, message
    except AssertionError as e:
        CrowdAiNotifier.notify()
        raise e
```
and then you can simply replace the assertions with 
```python
_assert( max(foo) < 1 , "maximum value in foo has to be less than 1" )
```

These error messages can then be provided as feedback to the participants when they fail.
(Only error messages from the trusted baseline models/attacks are shown as it is; and anything else is hidden from participants.)

**Comment by bveliqi** [comment]
@spMohanty Sounds good. Done. See PR #13.
